### PR TITLE
Text changed readOnly configuration section

### PR DESCRIPTION
**Pull request by antoniopol06**

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by ipeychev** [comment]
Thanks, pull request merged!

**Comment by ipeychev** [comment]
Hey @antoniopol06,

Thank you very much for the contribution! There was a problem - the changes you sent this time weren't rebased and there were a lot of conflicts. I rebased and resolved them, but could you rebase before sending, please?

Thanks,

**Comment by antoniopol06** [comment]
Hi @ipeychev sorry for that, it was my bad. I consider it for the next times =D.

**Pull request closed without merging**
