### PR TITLE
Reorder sections of guide page

### PR DESCRIPTION
**Pull request by antoniopol06**

### CODE REVIEW

**Comment by antoniopol06** [comment]
Hi @ipeychev , I have modified and  I have organized some  sections into guide and features pages. I continue to search more information that it can be added.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by ipeychev** [comment]
Thank you, Antonio!

And thank you for the contributions to AlloyEditor too!

@antoniopol06

**Comment by antoniopol06** [comment]
Hi @ipeychev , I want to add information about ReadOnly configuration. I thought that it could be fit in guide´s section in a new subsection that names "editor configurations" and into that appear list about editor configuration, in this case, ReadOnly configuration.  What do you think?

**Comment by ipeychev** [comment]
Hey Antonio,

That is a good idea! What other configurations might go in this new section?

Thanks,

**Comment by antoniopol06** [comment]
I thought that we can include toolbar configuration and buttons configuration. It will seem like a new section that names create. I feel that it can be more readability. During this week I try to add more info ;)

**Comment by ipeychev** [comment]
Okay, then, great!

**Pull request closed without merging**
